# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20161107_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'student_info',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
