# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20161107_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('fruit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Fruit')),
                ('custom', models.ManyToManyField(related_name='testapple', to='polls.Fruit')),
            ],
            bases=('polls.fruit',),
        ),
    ]
