# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_delete_ordertestproxy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestProxy',
            new_name='MyTestProxy',
        ),
        migrations.DeleteModel(
            name='MyTestProxy',
        ),
    ]
