# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_author_blog_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Question')),
                ('theme', models.CharField(max_length=200)),
            ],
            bases=('polls.question',),
        ),
    ]
