# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20161109_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='entity',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_set', to='polls.Blog'),
        ),
        migrations.AddField(
            model_name='entitydetail',
            name='aentity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Entity'),
        ),
    ]
