# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20161109_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='polls.Event')),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='entity',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_set', to='polls.Blog'),
        ),
    ]
