# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20161110_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='body_text',
        ),
        migrations.AddField(
            model_name='entity',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
