# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20161114_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
