# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_entity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('boys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Boy')),
            ],
        ),
        migrations.AlterField(
            model_name='entity',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
